import { 
  FileText, 
  Files, 
  Image as ImageIcon, 
  Scissors, 
  Minimize2, 
  Lock, 
  Unlock, 
  ScanText, 
  Sheet, 
  Presentation,
  FileType
} from 'lucide-react';
import { ToolDef, ToolCategory } from './types';

export const TOOLS: ToolDef[] = [
  // Utilities
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDFs into one unified document.',
    icon: Files,
    category: ToolCategory.UTILITIES,
    path: '/merge',
    accepts: '.pdf',
    outputType: 'application/pdf',
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Separate one page or a whole set for easy conversion.',
    icon: Scissors,
    category: ToolCategory.UTILITIES,
    path: '/split',
    accepts: '.pdf',
    outputType: 'application/zip',
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce file size while optimizing for maximal PDF quality.',
    icon: Minimize2,
    category: ToolCategory.UTILITIES,
    path: '/compress',
    accepts: '.pdf',
    outputType: 'application/pdf',
  },
  // Convert FROM PDF
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert your PDF to editable Word documents.',
    icon: FileText,
    category: ToolCategory.CONVERT_FROM_PDF,
    path: '/pdf-to-word',
    accepts: '.pdf',
    outputType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Pull data straight from PDFs into Excel spreadsheets.',
    icon: Sheet,
    category: ToolCategory.CONVERT_FROM_PDF,
    path: '/pdf-to-excel',
    accepts: '.pdf',
    outputType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Turn your PDF pages into high-quality JPG images.',
    icon: ImageIcon,
    category: ToolCategory.CONVERT_FROM_PDF,
    path: '/pdf-to-jpg',
    accepts: '.pdf',
    outputType: 'image/jpeg',
  },
  // Convert TO PDF
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    description: 'Convert JPG, PNG, BMP, and GIF images to PDF format.',
    icon: ImageIcon,
    category: ToolCategory.CONVERT_TO_PDF,
    path: '/image-to-pdf',
    accepts: '.jpg,.jpeg,.png,.bmp,.gif,.webp',
    outputType: 'application/pdf',
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Make DOC and DOCX files easy to read by converting them to PDF.',
    icon: FileType,
    category: ToolCategory.CONVERT_TO_PDF,
    path: '/word-to-pdf',
    accepts: '.doc,.docx',
    outputType: 'application/pdf',
  },
  {
    id: 'ppt-to-pdf',
    name: 'PowerPoint to PDF',
    description: 'Make PPT and PPTX slideshows easy to view by converting them to PDF.',
    icon: Presentation,
    category: ToolCategory.CONVERT_TO_PDF,
    path: '/ppt-to-pdf',
    accepts: '.ppt,.pptx',
    outputType: 'application/pdf',
  },
  // Security
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Encrypt your PDF with a password to keep sensitive data confidential.',
    icon: Lock,
    category: ToolCategory.SECURITY,
    path: '/protect',
    accepts: '.pdf',
    outputType: 'application/pdf',
  },
  // Features (Formerly PRO, now Free)
  {
    id: 'ocr-pdf',
    name: 'OCR PDF',
    description: 'Convert scanned PDFs and images into editable text documents.',
    icon: ScanText,
    category: ToolCategory.UTILITIES,
    path: '/ocr',
    accepts: '.pdf,.png,.jpg,.jpeg',
    outputType: 'text/plain',
  },
];

export const PLANS = [
  {
    name: 'Free Forever',
    price: '$0',
    period: '/ month',
    features: [
      'Access to all tools',
      'Unlimited document processing',
      'High-speed processing',
      'OCR (Optical Character Recognition)',
      'Batch processing (up to 10 files)',
      'Secure 256-bit Encryption',
      'No ads',
    ],
    cta: 'Start Now',
    isPrimary: true,
  },
];